name: svgaplayer_flutter
description: The SVGAPlayer implementation of Flutter using CustomPainter.
version: 2.1.2
homepage: https://github.com/yyued/SVGAPlayer-Flutter

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.1.0
  http: ^0.13.5
  path_drawing: ^1.0.0
  archive: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
